# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transferitem.ui'
#
# Created: Thu Jul 29 23:26:09 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TransferItem(object):
    def setupUi(self, TransferItem):
        TransferItem.setObjectName("TransferItem")
        TransferItem.resize(448, 96)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(TransferItem)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.content_frame = QtGui.QFrame(TransferItem)
        self.content_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.content_frame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_layout = QtGui.QHBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.main_icon = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_icon.sizePolicy().hasHeightForWidth())
        self.main_icon.setSizePolicy(sizePolicy)
        self.main_icon.setMinimumSize(QtCore.QSize(64, 0))
        self.main_icon.setMaximumSize(QtCore.QSize(64, 16777215))
        self.main_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.main_icon.setIndent(0)
        self.main_icon.setObjectName("main_icon")
        self.main_layout.addWidget(self.main_icon)
        self.labels_layout = QtGui.QVBoxLayout()
        self.labels_layout.setSpacing(0)
        self.labels_layout.setObjectName("labels_layout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filename = QtGui.QLabel(self.content_frame)
        self.label_filename.setObjectName("label_filename")
        self.horizontalLayout.addWidget(self.label_filename)
        spacerItem = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_status = QtGui.QLabel(self.content_frame)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)
        self.labels_layout.addLayout(self.horizontalLayout)
        self.from_layout = QtGui.QHBoxLayout()
        self.from_layout.setObjectName("from_layout")
        self.title_from = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_from.sizePolicy().hasHeightForWidth())
        self.title_from.setSizePolicy(sizePolicy)
        self.title_from.setMinimumSize(QtCore.QSize(40, 0))
        self.title_from.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.title_from.setFont(font)
        self.title_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.title_from.setObjectName("title_from")
        self.from_layout.addWidget(self.title_from)
        self.label_from = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_from.sizePolicy().hasHeightForWidth())
        self.label_from.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_from.setFont(font)
        self.label_from.setIndent(5)
        self.label_from.setObjectName("label_from")
        self.from_layout.addWidget(self.label_from)
        spacerItem1 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.from_layout.addItem(spacerItem1)
        self.label_duration = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_duration.sizePolicy().hasHeightForWidth())
        self.label_duration.setSizePolicy(sizePolicy)
        self.label_duration.setObjectName("label_duration")
        self.from_layout.addWidget(self.label_duration)
        self.label_sep = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sep.sizePolicy().hasHeightForWidth())
        self.label_sep.setSizePolicy(sizePolicy)
        self.label_sep.setObjectName("label_sep")
        self.from_layout.addWidget(self.label_sep)
        self.label_size = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_size.sizePolicy().hasHeightForWidth())
        self.label_size.setSizePolicy(sizePolicy)
        self.label_size.setObjectName("label_size")
        self.from_layout.addWidget(self.label_size)
        self.labels_layout.addLayout(self.from_layout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.title_to = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_to.sizePolicy().hasHeightForWidth())
        self.title_to.setSizePolicy(sizePolicy)
        self.title_to.setMinimumSize(QtCore.QSize(40, 0))
        self.title_to.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.title_to.setFont(font)
        self.title_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.title_to.setObjectName("title_to")
        self.horizontalLayout_4.addWidget(self.title_to)
        self.label_to = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_to.sizePolicy().hasHeightForWidth())
        self.label_to.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_to.setFont(font)
        self.label_to.setIndent(5)
        self.label_to.setObjectName("label_to")
        self.horizontalLayout_4.addWidget(self.label_to)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_timestamp = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timestamp.sizePolicy().hasHeightForWidth())
        self.label_timestamp.setSizePolicy(sizePolicy)
        self.label_timestamp.setObjectName("label_timestamp")
        self.horizontalLayout_4.addWidget(self.label_timestamp)
        self.labels_layout.addLayout(self.horizontalLayout_4)
        self.main_layout.addLayout(self.labels_layout)
        self.sync_icon = QtGui.QLabel(self.content_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_icon.sizePolicy().hasHeightForWidth())
        self.sync_icon.setSizePolicy(sizePolicy)
        self.sync_icon.setMinimumSize(QtCore.QSize(64, 0))
        self.sync_icon.setMaximumSize(QtCore.QSize(64, 16777215))
        self.sync_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.sync_icon.setIndent(0)
        self.sync_icon.setObjectName("sync_icon")
        self.main_layout.addWidget(self.sync_icon)
        self.horizontalLayout_3.addLayout(self.main_layout)
        self.horizontalLayout_2.addWidget(self.content_frame)

        self.retranslateUi(TransferItem)
        QtCore.QMetaObject.connectSlotsByName(TransferItem)

    def retranslateUi(self, TransferItem):
        TransferItem.setWindowTitle(QtGui.QApplication.translate("TransferItem", "TransferItem", None, QtGui.QApplication.UnicodeUTF8))
        TransferItem.setStyleSheet(QtGui.QApplication.translate("TransferItem", "QFrame#content_frame {\n"
"    border: 0px;\n"
"    border-bottom: 1px solid grey;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.466182, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.462312 rgba(34, 34, 34, 255), stop:1 rgba(22, 22, 22, 255));\n"
"}\n"
"\n"
"QLabel {\n"
"    color: rgb(229, 229, 229);\n"
"    font-size: 13pt;\n"
"}\n"
"\n"
"QLabel#label_filename {\n"
"    font-size: 17pt;\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel#title_from, #title_to {\n"
"    color: #0099FF;\n"
"    font: arial;\n"
"}\n"
"\n"
"QLabel#label_timestamp, #label_status, #label_duration, #label_size {\n"
"    font-size: 12pt;\n"
"    color: rgb(218, 218, 218);\n"
"}", None, QtGui.QApplication.UnicodeUTF8))
        self.label_filename.setText(QtGui.QApplication.translate("TransferItem", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("TransferItem", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.title_from.setText(QtGui.QApplication.translate("TransferItem", "from", None, QtGui.QApplication.UnicodeUTF8))
        self.label_from.setText(QtGui.QApplication.translate("TransferItem", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_duration.setText(QtGui.QApplication.translate("TransferItem", "duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sep.setStyleSheet(QtGui.QApplication.translate("TransferItem", "padding-left: 5px; padding-right: 5px;", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sep.setText(QtGui.QApplication.translate("TransferItem", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_size.setText(QtGui.QApplication.translate("TransferItem", "size", None, QtGui.QApplication.UnicodeUTF8))
        self.title_to.setText(QtGui.QApplication.translate("TransferItem", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_to.setText(QtGui.QApplication.translate("TransferItem", "path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_timestamp.setText(QtGui.QApplication.translate("TransferItem", "timestamp", None, QtGui.QApplication.UnicodeUTF8))

